#slimer

name: Build and deploy to ACR

env:
  PROJECT_NAME: slimer                            # set this to your project's name
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}                   # set this to the resource group containing your AKS cluster
  REGISTRY_URL: ${{ secrets.REGISTRY_LOGIN_SERVER }}              # set this to the URL of your registry

on:
  pull_request:
    types: [ closed, opened ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore ./slimer/slimer.sln
    - name: Build
      run: dotnet build slimer/slimer
    - name: Test with the dotnet CLI
      run: dotnet test slimer/slimer

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build -t ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}   

    - uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.PROJECT_NAME }}'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}